authentication_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path

from core.views import LoginView, SignUpView, IndexPage, LogoutView, ChangeLanguageView, ActivationView

app_name = 'core'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),

    path('register/', SignUpView.as_view(), name='register'),
    path('', IndexPage.as_view(), name='index'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('activate/<code>', ActivationView.as_view(), name='activate')
]

core/models.py
from django.contrib.auth.models import User
from django.db import models


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.forms import ValidationError
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class UserCacheMixin:
    user_cache = None


class SignIn(UserCacheMixin, forms.Form):
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if settings.USE_REMEMBER_ME:
            self.fields['remember_me'] = forms.BooleanField(label=_('Remember me'), required=False)

    def clean_password(self):
        password = self.cleaned_data['password']

        if not self.user_cache:
            return password

        if not self.user_cache.check_password(password):
            raise ValidationError(_('You entered an invalid password.'))

        return password


class SignInViaUsernameForm(SignIn):
    username = forms.CharField(label=_('Username'))

    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['username', 'password', 'remember_me']
        return ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']

        user = User.objects.filter(username=username).first()
        if not user:
            raise ValidationError(_('You entered an invalid username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return username


class EmailForm(UserCacheMixin, forms.Form):
    email = forms.EmailField(label=_('Email'))

    def clean_email(self):
        email = self.cleaned_data['email']

        user = User.objects.filter(email__iexact=email).first()
        if not user:
            raise ValidationError(_('You entered an invalid email address.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return email


class SignInViaEmailForm(SignIn, EmailForm):
    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['email', 'password', 'remember_me']
        return ['email', 'password']


class EmailOrUsernameForm(UserCacheMixin, forms.Form):
    email_or_username = forms.CharField(label=_('Email or Username'))

    def clean_email_or_username(self):
        email_or_username = self.cleaned_data['email_or_username']

        user = User.objects.filter(Q(username=email_or_username) | Q(email__iexact=email_or_username)).first()
        if not user:
            raise ValidationError(_('You entered an invalid email address or username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return email_or_username


class SignInViaEmailOrUsernameForm(SignIn, EmailForm):
    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['email_or_username', 'password', 'remember_me']
        return ['email_or_username', 'password']


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = settings.SIGN_UP_FIELDS

    email = forms.EmailField(label=_('Email'), help_text=_('Required. Enter an existing email address.'))

    def clean_email(self):
        email = self.cleaned_data['email']

        user = User.objects.filter(email__iexact=email).exists()
        if user:
            raise ValidationError(_('You can not use this email address.'))

        return email

core/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.utils.crypto import get_random_string
from django.views.generic import FormView, View, TemplateView

from django.contrib.auth.views import (
    LogoutView as BaseLogoutView
)

from core.utils import send_activation_email
from core.forms import SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm
from core.models import Activation

from django.utils.translation import gettext_lazy as _


class GuestOnlyVew(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user is already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LoginView(GuestOnlyVew, FormView):
    template_name = "login.html"

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    def form_valid(self, form):
        request = self.request

        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyVew, FormView):
    template_name = 'register.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(request, _('You are signed up. To active the account, follow the link sent to the mail.'))

        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up !'))

        return redirect('core:index')


class LogoutView(LoginRequiredMixin, BaseLogoutView):
    template_name = 'logout.html'


class IndexPage(TemplateView):
    template_name = 'index.html'


class ChangeLanguageView(TemplateView):
    template_name = 'change_language.html'


class ActivationView(View):

    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account !'))

        return redirect('core:login')

templates/change_language.html
{% extends 'page.html' %}

{% load i18n %}

{% block content %}

    {% get_current_language as language_code %}
    {% get_available_languages as languages %}

    <h4>{% trans 'Change language' %}</h4>

{#    <form action="{% url 'set_language' %}" method="post">#}
     <form action="#" method="post">

        {% csrf_token %}

        <input name="next" type="hidden" value="{{ redirect_to }}"/>

        <div class="form-group">
            <label class="form-control-label" for="language-field">{% trans 'Select the language' %}</label>
            <select name="language" class="form-control" id="language-field">
                {% for code, name in languages %}
                    <option value="{{ code }}" {% if code == language_code %} selected="selected"{% endif %}>
                        {{ name }} ({{ code }})
                    </option>
                {% endfor %}
            </select>
        </div>

        <button class="btn btn-success">{% trans 'Change' %}</button>

    </form>

{% endblock %}

templates/index.html
{% extends 'page.html' %}

{% load i18n %}

{% block content %}

    {% if request.user.is_authenticated %}

        {% trans 'Your username is' %} <b>{{ request.user.username }}</b>.

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

templates/login.html
{% extends 'page.html' %}

{% load bootstrap4 %}
{% load i18n %}


{% block content %}

    <h4>{% trans 'Log in' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Log in' %}</button>

    </form>

    <hr>

    <ul>
{#        <li>#}
{#            <a href="{% url 'accounts:restore_password' %}">{% trans 'Forgot your password?' %}</a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="{% url 'accounts:remind_username' %}">{% trans 'Forgot your username?' %}</a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="{% url 'accounts:resend_activation_code' %}">{% trans 'Resend an activation code' %}</a>#}
{#        </li>#}
    </ul>

{% endblock %}

templates/logout.html
{% extends 'page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'core:login' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

templates/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% bootstrap_css %}
{% bootstrap_jquery %}
{% bootstrap_javascript %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

{#    <link rel="icon" href="{% static 'favicon.ico' %}">#}

    <title>Simple Django Login and Registration</title>

{#    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">#}
{#    <link href="{% static 'css/styles.css' %}" rel="stylesheet">#}

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:login' %}">{% trans 'Django administration' %}</a>
                    </li>
                {% endif %}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>#}
{#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:logout' %}">{% trans 'Log out' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:login' %}">{% trans 'Log in' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:register' %}">{% trans 'Create an account' %}</a>
                </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:change_language' %}">{% trans 'Change language' %}</a>
            </li>
        </ul>
    </div>

</nav>

<div class="container-fluid mt-3">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>

{#<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>#}
{#<script src="{% static 'vendor/popper/popper.min.js' %}"></script>#}
{#<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>#}
{##}
{#<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>#}

</body>
</html>

templates/register.html
 {% extends 'page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Create an account' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-success">{% trans 'Create' %}</button>

    </form>

{% endblock %}